#!/usr/bin/python3

import datetime
import os
import sys

now = datetime.datetime.now()
timestamp = str(now.year) + str(now.month).zfill(2) + str(now.day).zfill(2)

client_name = "welltemperedtraveler_" + timestamp
os.system("source /etc/bash_completion.d/g4d && g4d -f " + client_name)

full_dest = os.path.join("/google/src/cloud/manucornet/", client_name, "google3/googledata/html/welltemperedtraveler")

if not os.path.exists(full_dest):
  print("I can't find the directory '" + full_dest + "'")
  sys.exit(1)

to_copy = [
  # Image
  "cold.png",
  "dot.png",
  "droplet.png",
  "favicon.png",
  "hot.png",
  "reset.png",
  # HTML
  "index.html",
  # Data
  "continents.txt",
  "ctry_codes.txt",
  "data.txt",
]

for f in to_copy:
  prev = os.getcwd()
  os.chdir(os.path.join("/google/src/cloud/manucornet/", client_name, "google3"))
  os.system("g4 edit googledata/html/welltemperedtraveler/" + f)
  os.chdir(prev)
  os.system("cp " + f + " " + full_dest)
