#!/usr/bin/python3

import datetime
import os
import sys

now = datetime.datetime.now()
timestamp = str(now.year) + str(now.month).zfill(2) + str(now.day).zfill(2)

client_name = "welltemperedtraveler_" + timestamp

full_dest = os.path.join("/google/src/cloud/manucornet/", client_name, "google3/googledata/html/welltemperedtraveler")
g3path = os.path.join("/google/src/cloud/manucornet/", client_name, "google3")

if not os.path.exists(full_dest):
  print("Please run this command then call me again from this directory:\n\ng4d -f " + client_name)
  sys.exit(1)

to_copy = [
  # Image
  "cold.png",
  "dot.png",
  "droplet.png",
  "favicon.png",
  "hot.png",
  "reset.png",
  # HTML
  "index.html",
  # Data
  "continents.txt",
  "ctry_codes.txt",
  "data.txt",
]

for f in to_copy:
  prev = os.getcwd()
  os.chdir(g3path)
  os.system("g4 edit googledata/html/welltemperedtraveler/" + f)
  os.chdir(prev)
  os.system("cp " + f + " " + full_dest)

print("\n\nNow please run:\n\ncd " + g3path + "\n\ng4 p\n\nAnd then\n\ng4 submit -c\n\nAnd then\n\ng4 citc -d g4test")
