NAMES = {
    "Atlanta|US": "ATLANTA NAS, G",
    "Berlin|DE": "BERLIN BUCH",
    "Bogotá|CO": "BOGOTA ELDORADO",
    "Brasília|BR": "BRASILIA",
    "Bridgetown|BB": "GRANTLEY ADAMS",
    # Might need to combine with CAIRO EZBEKIYA
    "Cairo|EG": "CAIRO ABBASSIA",
    "Frankfurt|DE": "FRANKFURT MAIN STADT",
    "Jakarta|ID": "JAKARTA TANJUNG PRIOK",
    "Kansas City|US": "KANSAS CITY BARRY HARBOR, M",
    "Los Angeles|US": "LOS ANGELES DOWNTOWN USC, C",
    "Miami|US": "MIAMI WEATHER SERVICE OFFICE CITY",
    "Quebec City|CA": "QUEBEC 2, Q",
    "Pittsburgh|US": "PITTSBURGH INTERNATIONAL AIRPORT, P",
    "Rome|IT": "ROMA CIAMPINO",
    # Might be more than one exact match?
    "São Paulo|BR": "SAO PAULO DO POTENGI",
    "West Island|CC": "COCOS ISLAND AERO",
}

NCEI_COUNTRY_CODES = {
    "BY": "BO",
    "CC": "CK",
    "CN": "CH",
    "DE": "GM",
    "ES": "SP",
    "JP": "JA",
    "KI": "KR",
    "LS": "LT",
    "LT": "LH",
    "MG": "MA",
    "MN": "MG",
    "NE": "NG",
    "NI": "NU",
    "RU": "RS",
    "SC": "SE",
    "SN": "SG",
    "SV": "ES",
    "TD": "CD",
}
